name: Deploy TourofHeroes to S3

# on:
#   workflow_dispatch:
#     inputs:
#       syslevel:
#         description: 'Target sys level'
#         required: true
#         default: 'ENG'
on:
  push:
    branches:
      - main
     
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13

      - name: Install dependencies
        env:
          LAST_NAME: Octocat
        run: npm install; npx ng build;

        # run: cd apps/frontend;npm install;npm run build:prod

      - name: Deploy
        if: success()
        # run: aws s3 sync ./dist/apps/apollo-ui/ s3://ideal-pancake
        run: aws s3 sync ./dist/angular-tour-of-heroes/dashboard s3://paige-tour-of-heroes/dashboard